sudo: false

language: ruby

rvm:
  - 2.4.0

env:
  - GIT_DEPLOY_REPO=https://$GITHUB_TOKEN@github.com/PunchShadow/slate.git

branches:
  only:
    - master

cache: bundler
script:
  - bundle exec middleman build
  - ./deploy.sh
